modLoader="javafml"
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]]
modId="tutorialmod"
version="1.0-1.20.1"
displayName="Tutorial Mod"
authors="Rick"
description='''Dit is een mod'''

[[dependencies.forge]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)" # Replace with the actual Minecraft version range
ordering="NONE"
side="BOTH"

# Uncomment and fill in additional fields if needed
# issueTrackerURL="https://example.com/issues"
# updateJSONURL="https://example.com/update.json"
# displayURL="https://example.com/modpage"
# logoFile="modlogo.png"
# credits=""

# Uncomment and set the displayTest field if needed
# displayTest="MATCH_VERSION"
